package entities;
// Generated Mar 20, 2019 10:46:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Devices generated by hbm2java
 */
@XmlRootElement
public class Devices  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Date dateInstall;
     private byte status;

    public Devices() {
    }

    public Devices(String name, Date dateInstall, byte status) {
       this.name = name;
       this.dateInstall = dateInstall;
       this.status = status;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateInstall() {
        return this.dateInstall;
    }
    
    public void setDateInstall(Date dateInstall) {
        this.dateInstall = dateInstall;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


