package entities;
// Generated Mar 20, 2019 10:46:05 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * User generated by hbm2java
 */
@XmlRootElement
public class User  implements java.io.Serializable {


     private Integer id;
     private String email;
     private String username;
     private String passWord;
     private Date dateSignup;

    public User() {
    }

    public User(String email, String username, String passWord, Date dateSignup) {
       this.email = email;
       this.username = username;
       this.passWord = passWord;
       this.dateSignup = dateSignup;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassWord() {
        return this.passWord;
    }
    
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }
    public Date getDateSignup() {
        return this.dateSignup;
    }
    
    public void setDateSignup(Date dateSignup) {
        this.dateSignup = dateSignup;
    }




}


